version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - WEBUI_SECRET_KEY=your-secret-key-here  # Change this in production
    volumes:
      - open_webui_data:/app/backend/data  # Persist chat history and settings
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    restart: unless-stopped

volumes:
  ollama_data:
  open_webui_data:  # Volume for Open WebUI data 